### ISSUE TITLE
automatically Pause when a player drops

### ISSUE THREAD

**Issue by mushis** [QW-Group/ktx#113]
I've seen this feature while watching a q2 clip on QuakeCon event.
here it is, quite funny 
https://www.twitch.tv/tastyspleentv/clip/ExpensiveZealousCaterpillarBibleThump

so, the player dropped, server pauses the game automatically. automatically resumes in 1 minute.
cool.
In qw, in that 1minute, someone can /elect and explicitly pause the game, then explicitly resume.
it's useful especially in tournaments, but nice in all games if you ask me.

**Comment by tcsabina** [comment]
I think this is not relevant anymore.
With #138, any player can pause during a match (if matchtag is set), so this auto-pause is not that appealing anymore.

Additionally, I have seen a conversation somewhere on discord about the possibility for the server to detect disconnection. And it is not that trivial.
The server could monitor each players PacketLoss level, but what should be the threshold for considering a Disconnect?

**Comment by blaps** [comment]
What about detecting idle players that doesn't do any input (mouse/kbd) for 10 seconds?

**Comment by tcsabina** [comment]
> What about detecting idle players that doesn't do any input (mouse/kbd) for 10 seconds?

Not sure what you are trying to say...
Auto-pause if there is a player who doesn't move the mouse or hit a key for 10 seconds? :)

I don't think that would solve any issue. Nowdays for serious games (read: tournament matches) all players are on voice, right? You know even before 10 seconds that someone dropped (because discord gives that 'player disconnected' tone)...

I can think of many more situations when this auto-pause could annoy/insult the running game, instead of offering something useful.
But I might be mistaken...
