### ISSUE TITLE
[BUG] coach names above enemies

### ISSUE THREAD

**Issue by namtsui** [QW-Group/ktx#130]
**Describe the bug**
Coaches in 4on4 can see names of opponents. This gives the ability to distinguish enemy players.

There are two possible advantages:
1. You can identify an enemy rocket out of two enemies, given they had fragged before.
2. An enemy rocket gets a frag, revealing the weapon, and goes somewhere else on the map. Names remove ambiguity as to whether an enemy has a weapon or not on this other part of the map.

**To Reproduce**
1. 4on4
2. Become coach
3. See enemy names

**Expected behavior**
Names should be hidden.

**Comment by meag** [comment]
Not an easy immediate fix I don't think - it's the client that's doing that (`/scr_autoid`), the client doesn't know that the coach isn't to have normal spectator features.

Only think I can think of to fix it server-side is hiding players from the packet to coaches and they get sent fake monster-like entities instead (as per fbca mod)?

**Comment by tcsabina** [comment]
As 'coaches' as there to train/teach players, I don't see this as a threat/issue. There are no serious games being played when a coach is selected. Most of the time, it is a friendly 2on2/4on4, to introduce QW to new players. I don't think any elected 'coach' could make a huge benefit because seeing the enemy players' name...

Closing as 'won't fix'.
