### ISSUE TITLE
[BUG] Limit elected admin privilages

### ISSUE THREAD

**Issue by tarbugre** [QW-Group/ktx#341]
**Describe the bug**
Elected admin can toggle nospecs and ban people

**To Reproduce**
1. be alone in a server
2. enable bots
3. addbots
4. gain admin by typing elect
5. type nospecs
6. ban users

**Expected behavior**
when alone a person can gain admin, but will lose admin once someone else joins server
elected admins cannot ban
elected admins cannot disable spectators

**What actually happens**
people can easily gain admin status when alonein server and mess with important configurations including banning

**Environment(please complete the following information):**
 - Operation System: [e.g. Windows, Linux, ...]
 - Processor Architecture: [e.g. x86, x86_64, arm7, ...]
 - MVDSV Version: mvdsv 0.35 antilag r115
 - KTX Version: 1.41 beta antilag r115

**Additional context**
workaround to avoid idiots

**Comment by suddendeathTV** [comment]
Haha funny way to elect admin!

I don't think you can actually ban people from the server through KTX admin like that, but I might be wrong. I think they're only timeouts but I may recall incorrectly

**Comment by ciscon** [comment]
so this is very strange, in StartFrame we have a vote_check_all which runs all the functions to check for votes, in all honesty i have absolutely no idea why this is run because voting initiates the individual calls anyway but someone must have had a reason to do it.  it appears that if you disable this, elect works as expected.  so one of these functions must muddle things up and not use the actual elect logic we see in vote.c:
  if (fofs == OV_ELECT)
  {
    vt_req = max(2, vt_req); // if election, at least 2 votes needed
  }

**Comment by tcsabina** [comment]
Fixed with #342
